[[dSFMT]]
arch = "aarch64"
git-tree-sha1 = "f93fa7147422e4ef8afb0981350cd196abab0bd7"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "64f557c987998dadc451d5f8d9e2161f68832008413697d3bf51e27d6defbebe"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.aarch64-linux-gnu.tar.gz"
[[dSFMT]]
arch = "aarch64"
git-tree-sha1 = "53138e329b8fc5fd1f02485884324a0494756643"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "02e7c8d1dcda89869e5c976d0ab45afd854336d11add6af3b954730fd1724c31"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.aarch64-linux-musl.tar.gz"
[[dSFMT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "25c8e52f28f7efe43c6f3c9b8bf3d8bf66fd081e"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "c245fe01285a0a9ce3c6eab94da5d69aa66ae4a39adaaf05f368602321e8d065"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.armv7l-linux-gnueabihf.tar.gz"
[[dSFMT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5f21efc353b11081308c976efc60ab947709283d"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "f0467fcaa025736b6938bfb7b4554d64be152c2436dcb8d4cb4635d981d73555"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.armv7l-linux-musleabihf.tar.gz"
[[dSFMT]]
arch = "i686"
git-tree-sha1 = "a59db76ee80d25bfa785f6c4d1be25df5ace6e63"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "f5bc175198ff55bb154297d5b3ca76d0ccf5dbf3ddb19bc0d5039ddb27ab726f"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.i686-linux-gnu.tar.gz"
[[dSFMT]]
arch = "i686"
git-tree-sha1 = "1e191de978f888472b0445a061f22432bff2945d"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "20187cf07cb110ac904386c8da0148bd46f909d0eb2e4b1b81d5da4c19ee2697"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.i686-linux-musl.tar.gz"
[[dSFMT]]
arch = "i686"
git-tree-sha1 = "991517d32cef075961c1a7e9d240e0e03f024049"
os = "windows"

    [[dSFMT.download]]
    sha256 = "aa3f5bcc83036dd17ba15eca464c5e3ffe0e4624e2e826c0e5b2958c078e3337"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.i686-w64-mingw32.tar.gz"
[[dSFMT]]
arch = "powerpc64le"
git-tree-sha1 = "e5c21db8786de7e00493c4720765f2201cff6a40"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "5caa934345fbe1731bad9ff41c3059b801c70937bd32fe8671e3158793ae3a95"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.powerpc64le-linux-gnu.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "80025531b9c4f418e4e2239465b62a94fc29e4d6"
os = "macos"

    [[dSFMT.download]]
    sha256 = "205ac74d24daf21e3f00dced1ccea2cabb1782bab7f569edec353da16cb59c47"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.x86_64-apple-darwin.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "ba9069e440a142519fa879805c412e09ca6b6bdc"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "ec104115493e0d1fdfb49e6105912ee7149345136ec6f8d3aab5e96104de5548"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.x86_64-linux-gnu.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "ea6bb4d9722d5d7b3d09dff2631e76100a353983"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "4f8102d2400d794e6e2be696b78914136fbfbd68b8f8371b787c189fa8bee5fb"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.x86_64-linux-musl.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "1718f56613bdd01f588dc0f909863c55500b3757"
os = "freebsd"

    [[dSFMT.download]]
    sha256 = "c5fe456f2222c70c4472346bc4c970f952c6c06831c74c25190b75f0afc4bf69"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.x86_64-unknown-freebsd.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "0bcb4a01922b60b9bdace167e25412534f4f4209"
os = "windows"

    [[dSFMT.download]]
    sha256 = "f8eb5c220e22cf35f834bad4e886cf9b69b80f07acce38e7c4ed77f17b11a4f2"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+2/dSFMT.v2.2.3.x86_64-w64-mingw32.tar.gz"
