[[dSFMT]]
arch = "aarch64"
git-tree-sha1 = "da39474c15e6aba8d629d2dc3176d2bfb0a34db6"
os = "macos"

    [[dSFMT.download]]
    sha256 = "28be6abb700ea076aba3bd8b22bb517f540c8324e4b3d5b7324f7bdc42cb3d01"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.aarch64-apple-darwin.tar.gz"
[[dSFMT]]
arch = "aarch64"
git-tree-sha1 = "d2cfbb941e59f75e1debdf74433426d176da7c51"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "364de174195fa6cb936cc21b7ca098e77bd0c92530581a839d739e5674abc56b"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.aarch64-linux-gnu.tar.gz"
[[dSFMT]]
arch = "aarch64"
git-tree-sha1 = "57457e32110c0cab05e502041999988345189c8e"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "719cca61de19b7032ddd61ab4273dbe35e8840b345ec9127dc21a5dc08d93b83"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.aarch64-linux-musl.tar.gz"
[[dSFMT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e510a73efe0753f393c4218f76c2ea98ae78825"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "a19127c773b112584c8af64672d014207e859076a30ddc4781264d0cab8bf8e9"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.armv6l-linux-gnueabihf.tar.gz"
[[dSFMT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e217be71b2cae12d87751befe387589746656c7c"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "84068e2533c39e9de8d234a3e66fb78269b2d156c226c552ec0316e7de736ccd"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.armv6l-linux-musleabihf.tar.gz"
[[dSFMT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2bd9811f9e052cd1c416333c39f29c0304461190"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "e2dd366f8df9fdc919404c4e18817cb06e05408ee842593c2e0b19a14da67145"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.armv7l-linux-gnueabihf.tar.gz"
[[dSFMT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1d53dc7125d3e47c3f94571f2c79e2ea74f77c3d"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "ddd843079cdf4fd219b2e98bab4a3cf32ff16aebe1874b2fd4d96cfb0f6547db"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.armv7l-linux-musleabihf.tar.gz"
[[dSFMT]]
arch = "i686"
git-tree-sha1 = "6eb1293f2e70df17ab3b62ca6e893f2961be4201"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "4a6be1055eec86f3ccc1aac21c54d85486d54a29335df7ad23a973d7e73ef89d"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.i686-linux-gnu.tar.gz"
[[dSFMT]]
arch = "i686"
git-tree-sha1 = "61612f7e0b67a210a331ae232ebe2d37a7527434"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "200275be5669f76a5894bbedd95e5b9f01605611351deacaf7a4e30e69f23e39"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.i686-linux-musl.tar.gz"
[[dSFMT]]
arch = "i686"
git-tree-sha1 = "4216cf377ea829aecfc83d2ff37dce5c23531a60"
os = "windows"

    [[dSFMT.download]]
    sha256 = "b8d1305208ac46d884eb9647b9747e7240801cfb91ba0b321555400d96016023"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.i686-w64-mingw32.tar.gz"
[[dSFMT]]
arch = "powerpc64le"
git-tree-sha1 = "5756ecad1c65892960f52fb49c6d2c1bd59d5d7c"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "c1c08e2d8fbc242302ce4ebb5b44b11013a838ff801d16cde2a8cb1ad85e5eae"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.powerpc64le-linux-gnu.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "41efdf2b2df369619b1704709c7ae1716589b65c"
os = "macos"

    [[dSFMT.download]]
    sha256 = "b7929e9bace6950cf3ae9a877f925e40954ce93249fe746727f705d174a7de9d"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.x86_64-apple-darwin.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "e5752ce5b1719951999ec90b1b35df5e0d83cba4"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "1e6537a1cfde608b2bb76900747613a1b28923e986b79f27232489c3b669207a"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.x86_64-linux-gnu.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "9bc520370b1efbd65f83d5209c20d28b7c9d4bb0"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "78b3afee46e83dce1d25e672b3d44ab743db101abbf5ba2ee548f47666276af7"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.x86_64-linux-musl.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "4c45140312d0cbdb88a198d9b176b97447bc1806"
os = "freebsd"

    [[dSFMT.download]]
    sha256 = "a9a567b5abae09c77ed51297a24a1090bdd28f755688d12af2ca62b7b55a1bfb"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.x86_64-unknown-freebsd.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "e313926f41cf3f178410f155bdd6cd28ad7055d3"
os = "windows"

    [[dSFMT.download]]
    sha256 = "d4d90abf970054509c834a7354dd3d3ef7df2c0060cc6f300d3c94f9509ce86c"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.4+1/dSFMT.v2.2.4.x86_64-w64-mingw32.tar.gz"
