[[dSFMT]]
arch = "aarch64"
git-tree-sha1 = "e6df872aeb9172f352bdfcc91c6485ddd3d6de22"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "8db031a5dabc21c3b2ffe23ff58437082cab1c6f0efb2e74c1a304dc3f94c905"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.aarch64-linux-gnu.tar.gz"
[[dSFMT]]
arch = "aarch64"
git-tree-sha1 = "e5db1672dcad82c717efde15b52335236414494b"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "cce590b241292079e5c3e5a7fe2705271597ee1a9905eb340b9322a158ede07c"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.aarch64-linux-musl.tar.gz"
[[dSFMT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1296f69e9273b731aa85a22d3ad36aeae995d4a2"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "3f9910d5efc6baff4880a1e562de935aefd489c17b46626645df0bee7533147b"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.armv7l-linux-gnueabihf.tar.gz"
[[dSFMT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9054fc20ecb438de18e47434fbadd3eb9ff746fd"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "a202b1944fa3ffdc0a6936fa521226bd9f31e22af15fd3e3992d4d25734a42a1"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.armv7l-linux-musleabihf.tar.gz"
[[dSFMT]]
arch = "i686"
git-tree-sha1 = "60ed4f0ae5e28b98648e4b3e08714c8b7ecb0e57"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "4b20935a8387bf5b51def32c840890094024a81f6731162c6364e79533c926ed"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.i686-linux-gnu.tar.gz"
[[dSFMT]]
arch = "i686"
git-tree-sha1 = "72f63d863fb4e1326d46a4c963957d702506b548"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "97ac95a85f1ed33827f4dfe03e5c1667d6b7a7e567b8935f2b38466518930aa4"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.i686-linux-musl.tar.gz"
[[dSFMT]]
arch = "i686"
git-tree-sha1 = "e6c60ca637912f3db586af9a8fd3dadff5578a47"
os = "windows"

    [[dSFMT.download]]
    sha256 = "97457f2e35f5c27ec4d8d9bf9385c1015e19545b35f48712d54a967af4a8bae5"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.i686-w64-mingw32.tar.gz"
[[dSFMT]]
arch = "powerpc64le"
git-tree-sha1 = "c7719f337795e93bd53619ab8363a8ab7d6eec20"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "5a03f00e9e8852a2bce084705c100c8f903373eb7d3b65ec4e2917236e0dd6ca"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.powerpc64le-linux-gnu.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "e26bd5f2f91e79035e641e9b9ea8f872e4e2e797"
os = "macos"

    [[dSFMT.download]]
    sha256 = "3137f19608028bc3fe32cb8b50a11d061d0231d8e029168a05a65440fc59cf06"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.x86_64-apple-darwin.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "8d60ed81bb1992f1be5c894c10f4c1fb64b9bf02"
libc = "glibc"
os = "linux"

    [[dSFMT.download]]
    sha256 = "dc72bf61008a7c3fc098aa6ddbfcaf5989fda61037fdd52567e8c5154bd2ace2"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.x86_64-linux-gnu.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "b486b8844e5fd20e7e749ba1e288f314a68bdf12"
libc = "musl"
os = "linux"

    [[dSFMT.download]]
    sha256 = "6560251ff60b903eb21393a8518528bf6f6bdfa3fd6cb39c5a84c132d8a433d3"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.x86_64-linux-musl.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "4954794e67ba98717dea79f6ec202d6040989360"
os = "freebsd"

    [[dSFMT.download]]
    sha256 = "586ee9a7589988caa58572531865f4c6c5b1a6ca9b2b2c9a1b025e8008ebeaa0"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.x86_64-unknown-freebsd.tar.gz"
[[dSFMT]]
arch = "x86_64"
git-tree-sha1 = "cecfe604fc14002b15a4154ca9559faf41eaccef"
os = "windows"

    [[dSFMT.download]]
    sha256 = "4452b2c6d201e95c0cf6958b17d05a41c32b18900ed58a41302c75d66fcaa8c9"
    url = "https://github.com/JuliaBinaryWrappers/dSFMT_jll.jl/releases/download/dSFMT-v2.2.3+3/dSFMT.v2.2.3.x86_64-w64-mingw32.tar.gz"
